### ISSUE TITLE
Hydrophobic moment is inconsistent with R version

### ISSUE THREAD

**Issue by eotovic** [althonos/peptides.py#1]
Computed hydrophobic moment is not the same as the one computed by R. More specifically, it seems that peptides.py always outputs 0 for the hydrophobic moment when peptide length is shorter than the set window. The returned value matches the value from R when peptide length is equal to or greater than the set window length.

Example in python:
```
>>> import peptides`
>>> peptides.Peptide("MLK").hydrophobic_moment(window=5, angle=100)
0.0
>>> peptides.Peptide("AACQ").hydrophobic_moment(window=5, angle=100)
0.0
>>> peptides.Peptide("FGGIQ").hydrophobic_moment(window=5, angle=100)
0.31847187610377536
```

Example in R:
```
> library(Peptides)
> hmoment(seq="MLK", window=5, angle=100)
[1] 0.8099386
> hmoment(seq="AACQ", window=5, angle=100)
[1] 0.3152961
> hmoment(seq="FGGIQ", window=5, angle=100)
[1] 0.3184719
```

I think that it can be easily fixed by internally setting the window length to the length of the peptide if the latter is shorter. What I propose:
```
--- a/peptides/__init__.py
+++ b/peptides/__init__.py
@@ -657,6 +657,7 @@ class Peptide(typing.Sequence[str]):
               :doi:`10.1073/pnas.81.1.140`. :pmid:`6582470`.

         """
+        window = min(window, len(self))
         scale = tables.HYDROPHOBICITY["Eisenberg"]
         lut = [scale.get(aa, 0.0) for aa in self._CODE1]
         angles = [(angle * i) % 360 for i in range(window)]
```

**Comment by althonos** [comment]
Good catch, thank you! I've made a new bugfix release with your suggested patch.
