### ISSUE TITLE
Per-residue data

### ISSUE THREAD

**Issue by multimeric** [althonos/peptides.py#3]
It seems that the API can only output single statistics for the entire peptide chain, but I'm interested in statistics for each residue individually. I'm wondering if it might be possible to output an array/list from some of these functions instead of always averaging them as is done now.

**Comment by althonos** [comment]
Hi @multimeric 

In `v0.3.0` I added the `Peptide.profile` function, which takes a per-residue table and an optional window size (default being 1, so no window averaging). You can get it to obtain per-residue data from any of the tables in `peptides.tables`, or from your own.

For instance, to get per-residue values of the VHSE1 descriptor:
```python
>>> p = peptides.Peptide("SDKEVDEVDAALSDLEITLE")
>>> p.profile(peptides.tables.VHSE["VHSE1"])
[-0.67, -1.15, -1.17, -1.18, 0.76, -1.15, -1.18, 0.76, -1.15, 0.15, 0.15, 1.36, -0.67, -1.15, 1.36, -1.18, 1.27, -0.34, 1.36, -1.18]
```
